backend:
  name: github
  repo: alexearnshaw/axway-open-docs # Path to your GitHub repository
  open_authoring: true

publish_mode: editorial_workflow

media_folder: "static/Images/uploads" # Media files will be stored in the repo under static/Images/uploads
public_folder: "/Images/uploads" # The src attribute for uploaded media will begin with /Images/uploads

site_url: https://fork-axway-open-docs.netlify.com/

collections: # A list of collections the CMS should be able to edit
  - name: "apimgr_concepts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "API management concepts" # Used in CMS UI left nav
    label_singular: "page in this section" # Used in CMS UI, ie.: "New Post"
    description: "All pages relating to API management concepts" # Used in CMS UI
    folder: "content/en/docs/apimgr_concepts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: false # Allow users to delete documents in this collection
    format: "json-frontmatter" # Specify frontmatter for YAML or json-frontmatter for JSON
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"} # Every collection must have a title field as it's the default identifier
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "apigtw_install" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Install API Gateway" # Used in CMS UI left nav
    label_singular: "page in this section" # Used in CMS UI, ie.: "New Post"
    description: "All pages relating to installing API Gateway and API Manager." # Used in CMS UI
    folder: "content/en/docs/apim_installation/apigtw_install" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: false # Allow users to delete documents in this collection
    format: "json-frontmatter" # Specify frontmatter for YAML or json-frontmatter for JSON
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"} # Every collection must have a title field as it's the default identifier
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}  
  - name: "apiportal_install"
    label: "Install or upgrade API Portal"
    label_singular: "page in this section"
    description: "All pages relating to installing or upgrading API Portal."
    folder: "content/en/docs/apim_installation/apiportal_install"
    create: true
    delete: false
    format: "json-frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "apigw_containers" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Deploy API Gateway in containers" # Used in CMS UI left nav
    label_singular: "page in this section" # Used in CMS UI, ie.: "New Post"
    description: "All pages relating to deploying API Gateway and API Manager in Docker containers." # Used in CMS UI
    folder: "content/en/docs/apim_installation/apigw_containers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: false # Allow users to delete documents in this collection
    format: "frontmatter" # Specify frontmatter for YAML or json-frontmatter for JSON
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"} # Every collection must have a title field as it's the default identifier
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"} 
  - name: "apiportal_docker"
    label: "Deploy API Portal in containers"
    label_singular: "page in this section"
    description: "All pages relating to deploying API Portal in containers."
    folder: "content/en/docs/apim_installation/apiportal_docker"
    create: true
    delete: false
    format: "json-frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}  
  - name: "apigw_upgrade"
    label: "Upgrade API Gateway"
    label_singular: "page in this section"
    description: "All pages relating to upgrading API Gateway."
    folder: "content/en/docs/apim_installation/apigw_upgrade"
    create: true
    delete: false
    format: "json-frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}   
  - name: "apigtw_devops"
    label: "Configure API Manager in multi-DC"
    label_singular: "page in this section"
    description: "All pages relating to configuring API Manager in multi-DC."
    folder: "content/en/docs/apigtw_devops"
    create: true
    delete: false
    format: "json-frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}   
  - name: "apiportal_ha"
    label: "Configure API Portal for HA"
    label_singular: "page in this section"
    description: "All pages relating to configuring API Portal for HA."
    folder: "content/en/docs/apiportal_ha"
    create: true
    delete: false
    format: "json-frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}    
  - name: "apigtw_devops"
    label: "Deploy to production"
    label_singular: "page in this section"
    description: "All pages relating to deploying API Gateway configuration."
    folder: "content/en/docs/apigtw_devops"
    create: true
    delete: false
    format: "json-frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}       
  - name: "apimanager_capacityguide"
    label: "Capacity planning and performance"
    label_singular: "page in this section"
    description: "All pages relating to capacity planning and performance tests."
    folder: "content/en/docs/apimanager_capacityguide"
    create: true
    delete: false
    format: "json-frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}   
  - name: "apimgmt_security"
    label: "Security guidance"
    label_singular: "page in this section"
    description: "All pages relating to security guidance for API Gateway, API Manager, and API Portal."
    folder: "content/en/docs/apimgmt_security"
    create: true
    delete: false
    format: "json-frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"} 
  - name: "apigtw_admin"
    label: "Administer API Gateway"
    label_singular: "page in this section"
    description: "All pages relating to administering API Gateway."
    folder: "content/en/docs/apim_administration/apigtw_admin"
    create: true
    delete: false
    format: "json-frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}   
  - name: "apimgr_admin"
    label: "Administer API Manager"
    label_singular: "page in this section"
    description: "All pages relating to administering API Manager."
    folder: "content/en/docs/apim_administration/apimgr_admin"
    create: true
    delete: false
    format: "json-frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"} 
  - name: "apimgr_admin_sso"
    label: "Administer API Manager (SSO)"
    label_singular: "page in this section"
    description: "All pages relating to administering API Manager SSO."
    folder: "content/en/docs/apim_administration/apimgr_admin/sso"
    create: true
    delete: false
    format: "json-frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}   
  - name: "apiportal_admin"
    label: "Administer API Portal"
    label_singular: "page in this section"
    description: "All pages relating to administering API Portal."
    folder: "content/en/docs/apim_administration/apiportal_admin"
    create: true
    delete: false
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "apiportal_admin_sso"
    label: "Administer API Portal (SSO)"
    label_singular: "page in this section"
    description: "All pages relating to administering API Portal SSO."
    folder: "content/en/docs/apim_administration/apiportal_admin/sso"
    create: true
    delete: false
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}                                    
  - name: "cass_admin" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Administer Apache Cassandra" # Used in CMS UI left nav
    label_singular: "page in this section" # Used in CMS UI, ie.: "New Post"
    description: "All pages relating to administering Apache Cassandra for API Gateway and API Manager." # Used in CMS UI
    folder: "content/en/docs/cass_admin" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: false # Allow users to delete documents in this collection
    format: "frontmatter" # Specify frontmatter for YAML or json-frontmatter for JSON
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"} # Every collection must have a title field as it's the default identifier
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "apiportal_releasenotes"
    label: "API Portal release notes"
    label_singular: "page in this section"
    description: "All pages relating to API Portal release."
    folder: "content/en/docs/apim_relnotes/apiportal_releasenotes"
    create: true
    delete: false
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "central"
    label: "AMPLIFY Central documentation"
    label_singular: "page in this section"
    description: "All pages relating to AMPLIFY Central."
    folder: "content/en/docs/central"
    create: true
    delete: false
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "contribution_guidelines"
    label: "Contribution guidelines"
    description: "All pages relating to contributing to the documentation."
    folder: "content/en/docs/contribution_guidelines"
    create: false
    delete: false
    format: "frontmatter"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "linkTitle", widget: "hidden", required: false}
      - {name: "no_list", widget: "hidden", required: false}
      - {name: "weight", widget: "hidden", required: false}
      - {name: "date", widget: "hidden", required: false}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}   
  - name: "newspost" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News posts" # Used in the UI, ie.: "New Post"
    label_singular: "News post"
    description: "All news posts."
    folder: "content/en/blog/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: false
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "releasepost" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Release posts" # Used in the UI, ie.: "New Post"
    label_singular: "Release post"
    description: "All product release posts."
    folder: "content/en/blog/releases" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: false
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}      
  - name: "friendspost" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Friends posts" # Used in the UI, ie.: "New Post"
    label_singular: "Friends post"
    description: "All friends of the doc posts."
    folder: "content/en/blog/friends" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: false
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Summary", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}      